#ifndef REQUESTS
#define REQUESTS

#define LOGIN_REQUEST "LOGIN"
#define REGISTER_REQUEST "REGISTER"
#define ADD_RECIPE_REQUEST "ADD_RECIPE"
#define DELETE_RECIPE_REQUEST "DELETE_RECIPE"
#define CHANGE_RECIPE_REQUEST "CHANGE_RECIPE"
#define GET_RECIPE_BY_OWNERS_ID_REQUEST "GET_RECIPE_BY_OWNERS_ID"
#define GET_RECIPE_BY_NAME_REQUEST "GET_RECIPE_BY_NAME"
#define GET_RECIPES_BY_NAME_REQUEST "GET_RECIPES_BY_NAME"
#define FILE_REQUEST "FILE"
#define GET_RECIPES_NEEDED_REQUEST "GET_RECIPES_NEEDED"
#define SEND_FILE_REQUEST "SEND_FILE"
#define ADD_RECIPE_TO_FAVOURITES_REQUEST "ADD_RECIPE_TO_FAVOURITES"
#define GET_FAVOURITE_RECIPES_REQUEST "GET_FAVOURITE_RECIPES"
#endif
